spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/chatdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    database: mysql
    # InnoDB : transaction
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl : true
    hibernate:
      ddl-auto: update
    show_sql: true

jwt:
  # chatserversecretaccesstokenchatserversecretaccesstokenchatserversecretaccesstoken
  secretKey: Y2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2VuY2hhdHNlcnZlcnNlY3JldGFjY2Vzc3Rva2Vu
  expiration: 3000 # ? ??